namespace Bitbucket.Cloud.Net.Models
{
	public enum WebhookEvents
	{
		PullRequestUnapproved,
		IssueCommentCreated,
		PullRequestApproved,
		RepoCreated,
		RepoDeleted,
		RepoImported,
		PullRequestCommentUpdated,
		IssueUpdated,
		ProjectUpdated,
		PullRequestCommentCreated,
		RepoCommitStatusUpdated,
		PullRequestUpdated,
		IssueCreated,
		RepoFork,
		PullRequestCommentDeleted,
		RepoCommitStatusCreated,
		RepoUpdated,
		PullRequestRejected,
		PullRequestFulfilled,
		RepoPush,
		PullRequestCreated,
		RepoTransfer,
		RepoCommitCommentCreated
	}
}
